- Maker/Assets/Scenes/Maker Main.unity
Small change in name to validate workflow
> further small check

- Maker/Assets/Code/DataPersistence/DataPersistenceManager.cs
- Maker/Assets/Code/ExitManager.cs
- Maker/Assets/Scenes/Maker Main.unity
> Twin 008a exit button removed

- Maker/Assets/Code/ItemText.cs
- Maker/Assets/Code/Sticker.cs
- Maker/Assets/Scenes/Maker Main.unity
https://maieutec-twin.atlassian.net/browse/TWIN-10
https://maieutec-twin.atlassian.net/browse/TWIN-14
https://maieutec-twin.atlassian.net/browse/TWIN-12
https://maieutec-twin.atlassian.net/browse/TWIN-15
> twin_010 save sticker

- Maker/Assets/Scenes/Maker Main.unity
https://maieutec-twin.atlassian.net/browse/TWIN-25
> twin_025 Save, load, select of texts not working properly

- Maker/Assets/Scenes/Maker Main.unity
https://maieutec-twin.atlassian.net/browse/TWIN-21
> twin_021 texts cut when placed

- Maker/Assets/Code/SetFontSize.cs
- Maker/Assets/Code/SetFontSize.cs.meta
- Maker/Assets/Scenes/Maker Main.unity
https://maieutec-twin.atlassian.net/browse/TWIN-26
> twin_026 change font size for text sticker

- Maker/Assets/Code/SetFontSize.cs
- Maker/Assets/Prefabs/Tool Paint Dynamic Decal.prefab
- Maker/Assets/Scenes/Maker Main.unity
https://maieutec-twin.atlassian.net/browse/TWIN-39
https://maieutec-twin.atlassian.net/browse/TWIN-26
> TWIN-39-Text-enter-and-size-disappeared

- Maker/Assets/Code/DataPersistence/DataPersistenceManager.cs
- Maker/Assets/Code/FileManager.cs
- Maker/Assets/Code/FileManager.cs.meta
- Maker/Assets/Code/PartManager.cs
- Maker/Assets/Code/SaveMode.cs
- Maker/Assets/Code/SaveMode.cs.meta
- Maker/Assets/Prefabs/GUI top.prefab
- Maker/Assets/Prefabs/Scroll two buttons and read only text.prefab
- Maker/Assets/Prefabs/Scroll two buttons and read only text.prefab.meta
- Maker/Assets/Scenes/Maker Main.unity
Parts of changes only. Before change to newer versions
> Twin 45 config data can be saved and loaded

- Maker/Assets/Code/Body.cs
- Maker/Assets/Code/DataPersistence/Data/ConfigData.cs
- Maker/Assets/Scenes/Maker Main.unity
TWIN-82-Body-position-is-not-saved
plus TWIN-81 Test 2 App reset Step 8 Body position is not reset to standard position after app reset
> TWIN-82-Body-position-is-not-saved

- Maker/Assets/Code/Model.cs
- Maker/Assets/Scenes/Maker Main.unity
Changed to toggle for arm and hands
> TWIN-75-arm-position

- Maker/Assets/Code/ToggleUpdater.cs
- Maker/Assets/Code/ToggleUpdater.cs.meta
- Maker/Assets/Prefabs/GUI top.prefab
- Maker/Assets/Scenes/Maker Main.unity
New Script which takes a Gameobject as reference and if the object to which is is displayed is enabled, it sets the toggle depending whether the reference is currently visible
> TWIN-95-show-checkboxes-are-inconsistent-within-the-different-modes

- Maker/Assets/Code/ViewManager.cs
- Maker/Assets/Scenes/Maker Main.unity
> TWIN-96-able-to-push-twin-out-of-view

- Maker/Assets/Scenes/Maker Main.unity
removed game object "shape" and attached text (two big blocks of deletions) 
replaced it with "link" prefab
> Twin 116 make shape button into prefab

- Maker/Assets/Material/icons/Binocularsses.png.meta
- Maker/Assets/Material/icons/Eye Inactive.png.meta
- Maker/Assets/Material/icons/Eye.png.meta
- Maker/Assets/Material/icons/Plus.png.meta
- Maker/Assets/Prefabs/Scroll text and toggle.prefab
- Maker/Assets/Prefabs/Scroll text and two buttons.prefab
- Maker/Assets/Scenes/Maker Main.unity
store view button, select view, hide/show group button were displayed as black boxes instead of icons (probably because I didn't push their meta files)
> Twin 138 black box instead of icon in overlays

- Maker/Assets/Prefabs/Icon in circle with text.prefab
- Maker/Assets/Prefabs/Icon in circle with text.prefab.meta
created prefab for edit menu, white circle with black icon and text with white background below
> Twin 134 prefab mode buttons

- Maker/Assets/Prefabs/GUI/Edit UI.prefab
- Maker/Assets/Prefabs/Icon in circle with text.prefab
- Maker/Assets/Scenes/Maker Main.unity
removed white bar in edit menu and changed buttons to icons in circle + text
> TWIN-147-NEW-LAYOUT-edit-ui-rework

- Maker/Assets/Code/Localization.meta
- Maker/Assets/Code/Localization/DateFormatter.cs
- Maker/Assets/Code/Localization/DateFormatter.cs.meta
- Maker/Assets/Code/Localization/LanguageSelector.cs
- Maker/Assets/Code/Localization/LanguageSelector.cs.meta
- Maker/Assets/Localization.meta
- Maker/Assets/Localization/Locales.meta
- Maker/Assets/Localization/Locales/English (en).asset
- Maker/Assets/Localization/Locales/English (en).asset.meta
- Maker/Assets/Localization/Locales/German (de).asset
- Maker/Assets/Localization/Locales/German (de).asset.meta
- Maker/Assets/Localization/LocalizationSettings.asset
- Maker/Assets/Localization/LocalizationSettings.asset.meta
- Maker/Assets/Localization/Table.meta
- Maker/Assets/Localization/Table/StringTable Shared Data.asset
- Maker/Assets/Localization/Table/StringTable Shared Data.asset.meta
- Maker/Assets/Localization/Table/StringTable.asset
- Maker/Assets/Localization/Table/StringTable.asset.meta
- Maker/Assets/Localization/Table/StringTable_de.asset
- Maker/Assets/Localization/Table/StringTable_de.asset.meta
- Maker/Assets/Localization/Table/StringTable_en.asset
- Maker/Assets/Localization/Table/StringTable_en.asset.meta
created new branch and added the files from TWIN-233 except for the third-party ones, trying to remove the third-party ones from TWIN-233 was too scary for me
> TWIN-233a-add-localization-table-english-german

- Maker/Assets/Code/ConfigManager.cs
- Maker/Assets/Code/SaveMode.cs
- Maker/Assets/Code/TwinNameValidator.cs
Test of valid twin name is now just executed as the button of new creation is pushed. Not any additional functionality. Tested on Twin Creation, Version Creation, Twin 'doubling', Version 'doubling, Twin deletion, Version deletion and complete reset of app.
> Twin 242 twin name will be checked first when button is pressed

- Maker/Assets/Localization/Locales/English (en).asset.meta
- Maker/Assets/Localization/Locales/German (de).asset.meta
- Maker/Assets/Localization/Table/StringTable Shared Data.asset
- Maker/Assets/Localization/Table/StringTable_de.asset
- Maker/Assets/Localization/Table/StringTable_en.asset
- Maker/Assets/Prefabs/GUI/Edit UI.prefab
- Maker/Assets/Prefabs/GUI/EditMarker UI.prefab
changes in first commit: had to make language files addressable, otherwise unity couldn't find/address them
added German translation to edit ui and maker ui 
added translation I forgot to translation table
> TWIN-246a-Translate-EditUI

- Maker/Assets/Scenes/Maker Main.unity
Removed 3 unused gameObjects in the SaveUI
> TWIN-288-Refactor-SaveUI

- Maker/Assets/Prefabs/GUI/Save UI.prefab
- Maker/Assets/Prefabs/GUI/Twin versions UI.prefab
- Maker/Assets/Prefabs/Scroll three buttons and three read only texts.prefab
- Maker/Assets/Scenes/Maker Main.unity
made spaces between buttons and text bigger, so "wählen" and "entfernen" wont overlap anymore
had to make width of scroll and panel object in SaveUI and VersionsUI bigger, so prefab could fit in it
> TWIN-286-Words-in-SaveUI-overlap-in-German

- Maker/Assets/Prefabs/GUI/Main UI.prefab
- Maker/Assets/Prefabs/GUI/Turn UI.prefab
- Maker/Assets/Scenes/Maker Main.unity
added on Click action and translation to default view button in mainUI and turnUI
> TWIN-297-default-view-button-does-not-work

- Maker/Assets/Code/SettingsManager.cs
- Maker/Assets/Prefabs/GUI/Settings UI.prefab
- Maker/Assets/Scenes/Maker Main.unity
set up new dropdown menu in the settings menu
deleted and inserted the sprites in the dropdown menu to try explicit including the sprites because unity couldn't create a link to both sprites, but the sprites in the dropdown menu are still missing - will work on this next week.
> TWIN-299-CORRECTION-add-switch-language-button-to-settings-page

- Maker/Assets/Scenes/Maker Main.unity
added missing onClick events in MenuUI and HelpUI
> TWIN-328-onclick-events-in-help-ui-are-missing

- Maker/Assets/Code/InteractionController.cs
- Maker/Assets/Code/PartManager.cs
- Maker/Assets/Code/PartsProcess.cs
- Maker/Assets/Code/PartsScreenshotProcess.cs
- Maker/Assets/Code/SceneManagement.cs
- Maker/Assets/Code/ViewManager.cs
- Maker/Assets/Prefabs/Scroll button and link and texts.prefab
- Maker/Assets/Scenes/Maker Main.unity
[TWIN-329-Fix-functionality-of-part-help-button-in-parts-detail-page](https://github.com/aschroff/twin/tree/TWIN-329-Fix-functionality-of-part-help-button-in-parts-detail-page)
> TWIN-329-Fix-functionality-of-part-help-button-in-parts-detail-page

- Maker/Assets/Prefabs/GUI/Main UI.prefab
- Maker/Assets/Prefabs/GUI/Turn UI.prefab
- Maker/Assets/Scenes/Maker Main.unity
- Maker/Assets/Tables/TwinLocalTables Shared Data.asset
- Maker/Assets/Tables/TwinLocalTables_de.asset
- Maker/Assets/Tables/TwinLocalTables_demed.asset
- Maker/Assets/Tables/TwinLocalTables_en.asset
- Maker/Assets/Tables/TwinLocalTables_enmed.asset
- loads of commits because I had to change a button functionality and I had to reset a few files because of merge conflicts:(
- added new 3 buttons to MainUI and TurnUI
- added translations for new buttons to localization table
- added onClick events (InteractionController.EnableMode()) in Maker Main
> TWIN-338-move-Help-Me-Versions-and-Parts-Page-to-view-submenu

- Maker/Assets/Prefabs/GUI/Twin versions UI.prefab
- Maker/Assets/Tables/TwinLocalTables Shared Data.asset
- Maker/Assets/Tables/TwinLocalTables_de.asset
- Maker/Assets/Tables/TwinLocalTables_demed.asset
- Maker/Assets/Tables/TwinLocalTables_en.asset
- Maker/Assets/Tables/TwinLocalTables_enmed.asset
Added locales for input field and buttons in Version UI
> TWIN-351-button-labels-in-Twin-Versions-UI-are-misleading
